[package]
name = "vendordeps"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
zip = "0.6"
thiserror = "1.0"
jwalk = "0.8"

[dev-dependencies]
tokio = { version = "1", features = ["rt"] }
tempfile = "3.9"