#[doc = "Create a [`VendorDep`] that includes all libraries that come with WPILib."]
pub fn wpilib_as_a_vendordep() -> VendorDep {
    VendorDep {
        file_name: "".to_string(),
        name: "".to_string(),
        version: crate::WPILIB_LATEST_VERSION.to_string(),
        frc_year: 2024,
        uuid: "".to_string(),
        maven_urls: vec![crate::WPILIB_RELEASE_MAVEN_REPO.to_string()],
        json_url: "".to_string(),
        conflicts_with: vec![],
        java_dependencies: vec![
            JavaDependency {
                group_id: "edu.wpi.first.fieldImages".to_string(),
                artifact_id: "fieldImages-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.apriltag".to_string(),
                artifact_id: "apriltag-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.wpimath".to_string(),
                artifact_id: "wpimath-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.cscore".to_string(),
                artifact_id: "cscore-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.cameraserver".to_string(),
                artifact_id: "cameraserver-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.wpiunits".to_string(),
                artifact_id: "wpiunits-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.wpilibj".to_string(),
                artifact_id: "wpilibj-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.ntcore".to_string(),
                artifact_id: "ntcore-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.wpiutil".to_string(),
                artifact_id: "wpiutil-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.hal".to_string(),
                artifact_id: "hal-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.wpilibNewCommands".to_string(),
                artifact_id: "wpilibNewCommands-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
            JavaDependency {
                group_id: "edu.wpi.first.wpinet".to_string(),
                artifact_id: "wpinet-java".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
            },
        ],
        jni_dependencies: vec![
            JniDependency {
                group_id: "edu.wpi.first.wpinet".to_string(),
                artifact_id: "wpinet-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
            JniDependency {
                group_id: "edu.wpi.first.apriltag".to_string(),
                artifact_id: "apriltag-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
            JniDependency {
                group_id: "edu.wpi.first.wpimath".to_string(),
                artifact_id: "wpimath-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
            JniDependency {
                group_id: "edu.wpi.first.wpiutil".to_string(),
                artifact_id: "wpiutil-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
            JniDependency {
                group_id: "edu.wpi.first.hal".to_string(),
                artifact_id: "hal-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
            JniDependency {
                group_id: "edu.wpi.first.ntcore".to_string(),
                artifact_id: "ntcore-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
            JniDependency {
                group_id: "edu.wpi.first.cscore".to_string(),
                artifact_id: "cscore-jni".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                is_jar: true,
                sim_mode: None,
                skip_invalid_platforms: false,
                valid_platforms: vec![],
            },
        ],
        cpp_dependencies: vec![
            CppDependency {
                group_id: "edu.wpi.first.wpinet".to_string(),
                artifact_id: "wpinet-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.wpilibNewCommands".to_string(),
                artifact_id: "wpilibNewCommands-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.ntcore".to_string(),
                artifact_id: "ntcore-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.fieldImages".to_string(),
                artifact_id: "fieldImages-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.apriltag".to_string(),
                artifact_id: "apriltag-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.cscore".to_string(),
                artifact_id: "cscore-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.hal".to_string(),
                artifact_id: "hal-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.wpimath".to_string(),
                artifact_id: "wpimath-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.wpiutil".to_string(),
                artifact_id: "wpiutil-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.ntcoreffi".to_string(),
                artifact_id: "ntcoreffi-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.cameraserver".to_string(),
                artifact_id: "cameraserver-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
            CppDependency {
                group_id: "edu.wpi.first.wpilibc".to_string(),
                artifact_id: "wpilibc-cpp".to_string(),
                version: crate::WPILIB_LATEST_VERSION.to_string(),
                header_classifier: "headers".to_string(),
            },
        ],
    }
}
